spring:
  application:
    name: Tas
  profiles:
    active: sample
    group:
        dev:
          - auth
          - databases
          - wallet
          - logging
          - spring-docs
          - notification
          - tas
        sample:
          - auth
          - databases-sample
          - wallet
          - logging
          - spring-docs
          - notification
          - tas
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090

kyc:
  url: http://127.0.0.1:8094/cas
