spring:
  application:
    name: Tas
  profiles:
    active: dev, test
    group:
        dev:
          - auth
          - databases
          - wallet
          - logging
          - spring-docs
          - notification
          - tas
          - setup
        sample:
          - auth
          - databases-sample
          - wallet
          - logging
          - spring-docs
          - notification
          - tas
          - setup
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "health,info"
#      base-path: "/tas/admin/v1"
#  endpoint:
#    health:
#      show-details: "always" # 모든 상태 정보 노출


server:
  port: 8090

kyc:
  url: http://127.0.0.1:8094/cas
