spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust:
            enable: true

fcm:
  enabled: false
  path:
  scope: https://www.googleapis.com/auth/cloud-platform

email:
  sender: "noreply_opendid@omnione.net"